Application --> Profs can mentor students whose grades are predicted low 

In [1]:
# loading the dataset and importing libraries 

import numpy as np 
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv('grades.csv')
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [ ]:
# This data is of a Portuguese school. 
'''
Grading System: 
    G1 -> grades fetched during the first period; 
    G2 -> grades fetched during the second period; 
    G3 -> final grades 
'''

In [6]:
# selecting the necessary columns to train the model 
# G3 is the target label 
# splitting the data into train and test subsets in the ratio of 80:20

data = data[['G1', 'G2', 'G3', 'studytime', 'failures', 'absences']]
predict = 'G3'
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2)

/var/folders/26/39vgl4bx79x6m4c_39t355mc0000gn/T/ipykernel_7173/3255889187.py:7: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = np.array(data.drop([predict], 1))


In [7]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
accuracy

0.8769538016342688

In [8]:
# accuracy is approx. 88%

In [9]:
# predictions
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 8.31457999  4.19751665 10.34077503  8.09604389  4.19751665]
 [ 8.31457999  8.31457999 10.34077503  8.09604389 14.94285993]
 [ 7.71889149  3.7751948  10.34077503  4.44481969 15.0490646 ]
 ...
 [15.0490646   3.7751948   9.83825704  4.44481969  4.44481969]
 [11.2410905  19.97832731  9.83825704  8.09604389  8.09604389]
 [ 3.7751948  11.7331998   9.83825704  8.09604389  8.31457999]] [[[ 8  9  2  0  4]
  [ 5  5  2  0 12]
  [11 11  4  0  8]
  [10  8  1  0 10]
  [ 5  5  2  0 12]]

 [[ 8  9  2  0  4]
  [ 8  9  2  0  4]
  [11 11  4  0  8]
  [10  8  1  0 10]
  [12 15  1  0  0]]

 [[11  8  2  0  2]
  [ 6  5  1  3 16]
  [11 11  4  0  8]
  [ 6  5  1  0  7]
  [14 15  2  0  2]]

 ...

 [[14 15  2  0  2]
  [ 6  5  1  3 16]
  [12 10  3  0 10]
  [ 6  5  1  0  7]
  [ 6  5  1  0  7]]

 [[10 12  2  1  4]
  [18 19  1  0  6]
  [12 10  3  0 10]
  [10  8  1  0 10]
  [10  8  1  0 10]]

 [[ 6  5  1  3 16]
  [12 12  2  0  0]
  [12 10  3  0 10]
  [10  8  1  0 10]
  [ 8  9  2  0  4]]] [array([[10,  5, 10,  9,  5]